### ISSUE TITLE
Bosce generates an unnamed state for transitions through a deep_history pseudo-state

### ISSUE THREAD

**Issue by EVictorson** [kanje/bosce#10]
I have a state with a custom reaction that returns a transit through a deep_history pseudo-state to a state we'll call Wait.  This section of code is:
sc::result Cooldown::react( const EvClear& )
{
  //does some stuff here
  return transit<sc::deep_history< Wait >>();
} 

But what is generated in the .pu file parsed by plantuml is an unnamed state entry with no other transitions.  It simply appends a state to the end of the list of states, in this case it's 14, and then just plots a state transition to state "14" in the UML diagram:

state "Cooldown" as 5 {  
  }  
  5 : Deferrals:  
  5 : * EvMove  
  5 : * EvStart  
  **5-->14 : EvClear\n**  
  5-->5 : EvRun\n  
  5-->6 : EvStop\n  
  5-->3 : EvQuit\n  
@enduml  

Is it possible for this to do something more informative like create an entry for history pseudo states, and then a transition from that history state to the state it indicates?  In this case it would be a transition from Cooldown -> History -> Wait.  See the example diagram under the "History" heading of the [state charts documentation](https://www.boost.org/doc/libs/1_39_0/libs/statechart/doc/tutorial.html#History)

**Comment by kanje** [comment]
Hi Eric! To be honest, I have never used history pseudo states, but I think that should be doable. Would it be possible for you to provide a minimal example to reproduce the issue (e.g. as shown [here](https://github.com/kanje/bosce#reporting-issues)). I probably can take the example from boost docs, but working with real code is always better.

**Comment by EVictorson** [comment]
Yep, give me just a little bit to get something over to you!

**Comment by EVictorson** [comment]
I figured I'd make it easy on you and just push their example with an added deep_history pseudo-state to [here](https://github.com/EVictorson/state_charts_examples/tree/main/Camera).  I've already generated the uml diagram in there as well.

**Comment by EVictorson** [comment]
For clarity, the effect the deep history pseudo state is, if you run the compiled example,  you can press c to enter the configuration state, then press h to enter the focusing state, and then press r to trigger the EvShutterRelease transition to the deep_history pseudo state, which will then return it to the configuring state, as opposed to going right to idle (which is currently configured as the default initial state to return to if there wasn't a previous state).

So you should see if you press 'h' and 'r' you leave Idle, leave NotShooting, enter Shooting, enter Focusing, then exit Shooting and enter NotShooting and Enter Idle (since that is the default initial state to return to).  If you instead press 'c', 'h', 'r', you should exit Idle, enter Configuring, then exit Configuring, exit NotShooting, enter Shooting, enter Focusing, then exit Shooting, enter NotShooting, and return to Configuring.

**Comment by kanje** [comment]
Thanks for the input! Will do my best to implement it :)

**Comment by EVictorson** [comment]
Let me know if there's anything I can do to help!

**Comment by kanje** [comment]
Looks good?
![img](https://user-images.githubusercontent.com/11983265/146616839-872b5ef5-7fef-477b-95f4-a3c35009217e.png)

**Comment by kanje** [comment]
@EVictorson, could you please check if PR #12 works for you?

**Comment by EVictorson** [comment]
On it, sorry for the delay, I've been sick the past few days.

That diagram looks great, though!

**Comment by EVictorson** [comment]
I've commented on the PR, but plantuml is bombing out in trying to generate a digram from the generated .pu file.  Take a look at the contents and see if they're the same as yours for that stopwatch example.
