### ISSUE TITLE
Error while parsing binary

### ISSUE THREAD

**Issue by AugusteBourgois** [kanje/bosce#17]
Hi there,

I just discovered your tool thanks to your "Meeting C++ 2019" video, and I really look forward to using it in my project.

I tried to parse my binary file, built using the Debug symbols, but the parsing stops quickly and fails with `Error: map::at`.
I then tried to simply extract the objdump from my binary, which works without any problems, but leads to the same error when parsing the generated objdump file.

The beginning of the UML description is generated, but is interrupted when the error occurs.

For information, my state machine uses orthogonal states, deep history and `boost::statechart::state` (as opposed to `boost::statechart::simple_state`). It also uses parametrized states as described in the tutorial [Submachines & parameterized states](https://www.boost.org/doc/libs/1_76_0/libs/statechart/doc/tutorial.html#SubmachinesAndParameterizedStates)

Do you have any idea of what might be happening ? Should you need any other information, please let me know. I'd be happy to help solving the problem.

Thank you in advance for your help !

Below are the generated uml file and the stripped objdump file.

[uml.pu.txt](https://github.com/kanje/bosce/files/8213615/uml.pu.txt)
[stripped.objdump.txt](https://github.com/kanje/bosce/files/8213613/stripped.objdump.txt)

**Comment by kanje** [comment]
Hi, thanks for your message! I have just reproduced it locally, so there should be no issue to fix it. I will have a look at this during the weekend.

**Comment by AugusteBourgois** [comment]
Thanks for your reply !

I can send you a diagram of the actual state machine if required.

**Comment by kanje** [comment]
~I have some issues with history states. Still trying to fix it. Does this diagram look somewhat like you would expect?~

It seems I have solved the history state issues. Is this diagram correct?

![diagram](https://user-images.githubusercontent.com/11983265/158201714-05260f8c-e8ad-4f47-b1cf-5f15ba22d8a1.png)

**Comment by kanje** [comment]
It seems I have solved the history state issues. Is this diagram correct?

![diagram](https://user-images.githubusercontent.com/11983265/158201714-05260f8c-e8ad-4f47-b1cf-5f15ba22d8a1.png)

**Comment by AugusteBourgois** [comment]
Yes, absolutely ! Thank you very much for taking the time to solve my problem ! I really appreciate it.

**Comment by kanje** [comment]
Good. I will need some time to clean up the code a bit. If you want, I can also upload a "dirty" version so you can already start using it.

**Comment by AugusteBourgois** [comment]
I can wait until you upload the clean version. Please let me know. Thank you again !

**Comment by kanje** [comment]
@AugusteBourgois, please see if https://github.com/kanje/bosce/pull/18 works for you. If it does, I will merge it.

This PR also:
- Contains your state machine as a unit test. Is it fine? Or should I make a synthetic test?
- Removes all namespaces. Note, previously only the "main" namespace was removed but e.g. not namespaces in template parameters.

**Comment by AugusteBourgois** [comment]
It works for me, thank you !
You can keep my state machine as a unit test.

Also, good idea of removing all namespaces, the output would have been quite hard to understand otherwise.
